# Generated by Django 5.1.1 on 2025-10-16 08:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, unique=True, verbose_name='عبارت جستجو')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='تعداد جستجو')),
                ('last_searched', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین جستجو')),
            ],
            options={
                'verbose_name': 'جستجوی پرتکرار',
                'verbose_name_plural': 'جستجوهای پرتکرار',
                'ordering': ['-count', '-last_searched'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, verbose_name='عبارت جستجو')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ جستجو')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='کلید نشست')),
            ],
            options={
                'verbose_name': 'تاریخچه جستجو',
                'verbose_name_plural': 'تاریخچه جستجوها',
                'ordering': ['-created_at'],
            },
        ),
    ]
