# Generated by Django 5.1.1 on 2025-10-16 08:34

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='authors/avatars/')),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات ')),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('reading_time', models.PositiveSmallIntegerField(blank=True, help_text='Approx minutes. Optional.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-publish_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='MetaTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='یک نام توصیفی برای این مجموعه متا تگ', max_length=200, verbose_name='نام متا تگ')),
                ('title', models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر - برای SEO', max_length=60, verbose_name='متا تایتل')),
                ('description', models.TextField(blank=True, help_text='حداکثر ۱۶۰ کاراکتر - برای SEO', max_length=160, verbose_name='متا دیسکریپشن')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='نویسنده')),
                ('copyright', models.CharField(blank=True, max_length=100, verbose_name='کپی رایت')),
                ('robots', models.CharField(blank=True, default='index, follow', help_text='مثال: noindex, nofollow', max_length=100, verbose_name='ربات\u200cها')),
                ('og_title', models.CharField(blank=True, help_text='حداکثر ۹۰ کاراکتر - برای شبکه\u200cهای اجتماعی', max_length=90, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, help_text='حداکثر ۲۰۰ کاراکتر - برای شبکه\u200cهای اجتماعی', max_length=200, verbose_name='OG Description')),
                ('og_image', models.ImageField(blank=True, help_text='تصویر برای نمایش در شبکه\u200cهای اجتماعی', null=True, upload_to='meta/og_images/', verbose_name='OG Image')),
                ('og_type', models.CharField(blank=True, default='website', help_text='مثال: article, website, product', max_length=50, verbose_name='OG Type')),
                ('og_url', models.URLField(blank=True, verbose_name='OG URL')),
                ('twitter_card', models.CharField(blank=True, default='summary_large_image', help_text='summary, summary_large_image, app, player', max_length=50, verbose_name='Twitter Card Type')),
                ('twitter_site', models.CharField(blank=True, help_text='مانند: @username', max_length=100, verbose_name='Twitter Site')),
                ('twitter_creator', models.CharField(blank=True, help_text='مانند: @username', max_length=100, verbose_name='Twitter Creator')),
                ('twitter_title', models.CharField(blank=True, help_text='حداکثر ۷۰ کاراکتر', max_length=70, verbose_name='Twitter Title')),
                ('twitter_description', models.TextField(blank=True, help_text='حداکثر ۲۰۰ کاراکتر', max_length=200, verbose_name='Twitter Description')),
                ('twitter_image', models.ImageField(blank=True, null=True, upload_to='meta/twitter_images/', verbose_name='Twitter Image')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('content_type', models.CharField(blank=True, default='text/html; charset=utf-8', max_length=50, verbose_name='Content Type')),
                ('viewport', models.CharField(blank=True, default='width=device-width, initial-scale=1.0', max_length=100, verbose_name='Viewport')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meta Tags',
                'verbose_name_plural': 'Meta Tags',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
