# Generated by Django 5.1.1 on 2025-10-16 08:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peyment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ساخته شده')),
                ('updateAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('amount', models.IntegerField(verbose_name='مبلغ پرداخت')),
                ('description', models.TextField(verbose_name='توضیحات پرداخت')),
                ('isFinaly', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('statusCode', models.IntegerField(blank=True, null=True, verbose_name='کد وضعیت پرداخت')),
                ('refId', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پیگیری پرداخت')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
    ]
