# Generated by Django 5.1.1 on 2025-10-16 08:34

import django.utils.timezone
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameBanner', models.CharField(max_length=100, verbose_name='نام بنر')),
                ('textBanner', models.CharField(max_length=300, verbose_name='متن بنر')),
                ('altSlide', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوشتار عکس')),
                ('imageName', models.ImageField(upload_to=utils.FileUpload.upload_to)),
                ('isActive', models.BooleanField(default=False)),
                ('registerData', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('endData', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پایان')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
            },
        ),
        migrations.CreateModel(
            name='SliderMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textSlider', models.CharField(max_length=100, verbose_name='متن اسلایدر')),
                ('imageName', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='عکس اسلایدر')),
                ('altSlide', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوشتار عکس')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('registerData', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('endData', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پایان')),
                ('link', models.CharField(blank=True, max_length=300, null=True, verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'اسلایدر مرکز',
                'verbose_name_plural': 'اسلایدرها مرکز ها',
            },
        ),
        migrations.CreateModel(
            name='SliderSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textSlider', models.CharField(max_length=100, verbose_name='متن اسلایدر')),
                ('imageName', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='عکس اسلایدر')),
                ('altSlide', models.CharField(max_length=100, verbose_name='نوشتار عکس')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('registerData', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('endData', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پایان')),
                ('link', models.CharField(blank=True, max_length=300, null=True, verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
            },
        ),
    ]
